### ISSUE TITLE
Send Confirmation Dialog: Display calculated fee

### ISSUE THREAD

**Issue by jojobyte** [dashhive/wallet-ui#55]
We need to display the fee for the transaction and possibly update the amount to what will actually be sent.

**Comment by riongull** [comment]
It's an improvement but "full amount" is incorrect. 

![image](https://github.com/dashhive/wallet-ui/assets/6496310/3f61a12c-c368-4916-8603-61629614de3a)

In terms of style I'd make the top line "To recipient(s)", the next line "Network fee" (keep it smaller font), and then "Total" at the bottom.

**Comment by riongull** [comment]
Subsequent screenshots 
- one confirm from above tx
- one addition tx with confirm

![image](https://github.com/dashhive/wallet-ui/assets/6496310/321b1828-9aa4-478f-911d-9a5b963e2e84)

![image](https://github.com/dashhive/wallet-ui/assets/6496310/ec365bba-3264-41fe-80d8-1ed1629e7ee1)

![image](https://github.com/dashhive/wallet-ui/assets/6496310/2c7e001c-f423-428b-829f-5699c22ed4fe)

**Comment by jojobyte** [comment]
@riongull please review this feature/functionality again at https://fix-dashwallet-implementation.wallet.dashincubator.dev/ and change Status to Done if you approve or back to "In Progress" if it needs more work.

**Comment by riongull** [comment]
I'd like to gray out insignificant figures here like we do in the main balance screen.  So for now, make the last 5 digits gray.

After mulling it over, I think we talk with @coolaj86 about potentially changing the significant figures:

- It might be better to split the significant-insignificant digits to 4-4 instead of our current 3-5.
- I'd like the maximum insignificant digit to have less than 1 USD cent of value.
- Right now the max insignificant digit would be 0.000 90000 (highest value of first insignificant figure)
- At the current 40 USD/DASH that is 40 x 0.000 90000 = $0.036 (3.6 cents USD).
- If we shift it one place the max insignificant digit would be 0.0000 9000
- Then even at 100 USD/DASH it would be 100 x 0.0000 9000 = $0.009 (<1 cent USD).
- 4-4 is more significant digits to track mentally, but it's more balanced than 3-5, so I think easier to work with overall.

From testing (and conversations with AJ) it seems the denominated tx handling makes "stamps" of 200 sats each (where each send uses at least 200 sats, sometimes 400 or more, but it seems multiples of 200).  When people are using that option it will be easier for them to see a value of 1.0000 5600 and have a better "gut feel" that I can send this 1 DASH 20 or so times without the face value (the significant figure - 1.0000) changing.  We'll need to talk this over with @coolaj86, because there are nuances about how the library works that might need to change to facilitate this.

For now just make the simple UI change to gray the last 5 digits.  We can copy the above to a new issue to address the bigger change.

**Comment by jojobyte** [comment]
@riongull this is implemented by https://github.com/dashhive/wallet-ui/pull/64/commits/668bad3b3a809c2921892acd7470566fd4386f89 at https://feat-surface-errors.wallet.dashincubator.dev/.

Closing this issue and setting status to Done.
